const fs = require('node:fs')
const path = require('node:path')

function extract(file, name) {
  const source = fs.readFileSync(file, 'utf8')
  const prefix = `export const ${name} = JSON.parse('`
  const start = source.indexOf(prefix)
  if (start < 0) throw new Error(`Unable to find ${name} in ${file}`)
  const payloadStart = start + prefix.length
  const end = source.indexOf("') as ", payloadStart)
  if (end < 0) throw new Error(`Unable to find the end of ${name} in ${file}`)
  const literal = `'${source.slice(payloadStart, end)}'`
  return JSON.parse(Function(`"use strict"; return ${literal}`)())
}

function jsString(value) {
  return JSON.stringify(value)
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029')
}

const works = extract('src/data/works.ts', 'works')
const chapters = extract('src/data/works.ts', 'chapters')
const passages = [
  ...extract('src/data/sentence_chunks/passages_part1.ts', 'passagesPart1'),
  ...extract('src/data/sentence_chunks/passages_part2.ts', 'passagesPart2'),
]
const sentences = Array.from({ length: 8 }, (_, index) =>
  extract(`src/data/sentence_chunks/part${index + 1}.ts`, `sentencesPart${index + 1}`),
).flat()

const chapterWork = new Map(chapters.map(chapter => [chapter.id, chapter.workId]))
const passageWork = new Map(passages.map(passage => [passage.id, chapterWork.get(passage.chapterId)]))
const outDir = 'src/data/work_chunks'
fs.mkdirSync(outDir, { recursive: true })

for (const entry of fs.readdirSync(outDir)) {
  if (entry.endsWith('.ts')) fs.unlinkSync(path.join(outDir, entry))
}

for (const work of works) {
  const workChapters = chapters.filter(chapter => chapter.workId === work.id)
  const chapterIds = new Set(workChapters.map(chapter => chapter.id))
  const workPassages = passages.filter(passage => chapterIds.has(passage.chapterId))
  const passageIds = new Set(workPassages.map(passage => passage.id))
  const workSentences = sentences.filter(sentence => passageIds.has(sentence.passageId))
  const payload = { work, chapters: workChapters, passages: workPassages, sentences: workSentences }
  const content = `import type { WorkBundle } from '../workLoader'\n\nexport default JSON.parse('${jsString(payload)}') as WorkBundle\n`
  fs.writeFileSync(path.join(outDir, `${work.id}.ts`), content, 'utf8')
}

const loaderEntries = works
  .map(work => `  '${work.id}': () => import('./work_chunks/${work.id}'),`)
  .join('\n')
const manifest = `// Generated by scripts/generate_work_chunks.cjs\nexport const workImports = {\n${loaderEntries}\n} as const\n`
fs.writeFileSync('src/data/workImportManifest.ts', manifest, 'utf8')
console.log(`Generated ${works.length} independent work modules from ${chapters.length} chapters, ${passages.length} passages and ${sentences.length} sentences.`)
