import fs from 'node:fs'
import path from 'node:path'

function extract(file: string, name: string) {
  const source = fs.readFileSync(file, 'utf8')
  const prefix = `export const ${name} = JSON.parse('`
  const start = source.indexOf(prefix)
  if (start < 0) throw new Error(`Unable to find ${name} in ${file}`)
  const payloadStart = start + prefix.length
  const end = source.indexOf("') as ", payloadStart)
  let literal = '';
  if (end < 0) {
      const end2 = source.indexOf("')", payloadStart);
      if (end2 < 0) throw new Error(`Unable to find the end of ${name} in ${file}`);
      literal = `'${source.slice(payloadStart, end2)}'`;
  } else {
      literal = `'${source.slice(payloadStart, end)}'`;
  }
  return JSON.parse(new Function(`"use strict"; return ${literal}`)())
}

function jsString(value: any) {
  return JSON.stringify(value)
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029')
}

const CANONICAL_ORDER = [
  // 儒家 (Confucianism)
  'lun-yu',
  'meng-zi',
  'da-xue',
  'zhong-yong',
  'xunzi',
  'yi-jing',
  'shu-jing',
  'shi-jing',
  'li-ji',
  'chun-qiu',

  // 道家 (Daoism)
  'dao-de-jing',
  'zhuangzi',
  'liezi',
  'wenzi',
  'wenshi-zhenjing',

  // 法家 (Legalism)
  'han-fei-zi',
  'shang-jun-shu',
  'shen-bu-hai',
  'shenzi',
  'jian-zhu-ke-shu',
  'guanzi',

  // 墨家 (Mohism)
  'mo-zi',

  // 兵家 (Military)
  'art-of-war',
  'wu-zi',
  'si-ma-fa',
  'three-strategies',
  'wei-liao-zi',
  'liu-tao',

  // 史書 (Histories)
  'shiji',
  'chun-qiu-zuo-zhuan',
  'zhan-guo-ce',
  'yan-tie-lun',
  'yandanzi',
  'xijing-zaji',
  'lost-book-of-zhou',
  'guo-yu',
  'yanzi-chun-qiu',
  'wu-yue-chun-qiu',
  'yue-jue-shu',
  'lie-nv-zhuan',
  'guliang-zhuan',
  'gongyang-zhuan',
  'han-shu',
  'hou-han-shu',
  'qian-han-ji',
  'dong-guan-han-ji',
  'zhushu-jinian',
  'mutianzi-zhuan',
  'gu-san-fen',

  // 文學 (Literature)
  'gu-wen-guan-zhi',
  'cai-gen-tan'
];

const subtitles: Record<string, string> = {
  'dao-de-jing': '老子',
  'zhuangzi': '南華真經',
  'liezi': '沖虛至德真經',
  'shang-jun-shu': '商鞅及其後學',
  'mo-zi': '墨翟及墨家後學',
  'art-of-war': '孫武',
  'wu-zi': '吳起',
  'three-strategies': '黃石公三略',
  'liu-tao': '太公兵法',
  'zhan-guo-ce': '劉向編定',
  'xunzi': '荀況著',
  'cai-gen-tan': '洪應明',
  'yanzi-chun-qiu': '晏嬰'
};

// Data sources
const rawWorks = extract('data_sources/works.ts', 'works')
const chapters = extract('data_sources/works.ts', 'chapters')
const passages = [
  ...extract('data_sources/sentence_chunks/passages_part1.ts', 'passagesPart1'),
  ...extract('data_sources/sentence_chunks/passages_part2.ts', 'passagesPart2'),
]
const sentences = Array.from({ length: 8 }, (_, index) =>
  extract(`data_sources/sentence_chunks/part${index + 1}.ts`, `sentencesPart${index + 1}`),
).flat()

// Import reading aids directly using TS
import { PASSAGE_AIDS } from '../src/data/readingAid'

const works = rawWorks
  .map((w: any) => {
    let title = w.title;
    if (!title.startsWith('《')) {
      title = `《${title}》`;
    }
    return {
      ...w,
      title,
      ...(subtitles[w.id] && !w.subtitle ? { subtitle: subtitles[w.id] } : {})
    };
  })
  .sort((a: any, b: any) => {
    const idxA = CANONICAL_ORDER.indexOf(a.id);
    const idxB = CANONICAL_ORDER.indexOf(b.id);
    return (idxA >= 0 ? idxA : 999) - (idxB >= 0 ? idxB : 999);
  });

const outDir = 'src/data/work_chunks'
if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true })
}

for (const entry of fs.readdirSync(outDir)) {
  if (entry.endsWith('.ts')) fs.unlinkSync(path.join(outDir, entry))
}

for (const work of works) {
  const workChapters = chapters.filter((chapter: any) => chapter.workId === work.id)
  const chapterIds = new Set(workChapters.map((chapter: any) => chapter.id))
  const workPassages = passages.filter((passage: any) => chapterIds.has(passage.chapterId))
  
  // Inject reading aids into passages directly
  for (const p of workPassages) {
      if ((PASSAGE_AIDS as any)[p.id]) {
          p.readingAid = (PASSAGE_AIDS as any)[p.id];
      }
  }
  
  const passageIds = new Set(workPassages.map((passage: any) => passage.id))
  const workSentences = sentences.filter((sentence: any) => passageIds.has(sentence.passageId))
  const payload = { work, chapters: workChapters, passages: workPassages, sentences: workSentences }
  const content = `import type { WorkBundle } from '../workLoader'\n\nexport default JSON.parse('${jsString(payload)}') as WorkBundle\n`
  fs.writeFileSync(path.join(outDir, `${work.id}.ts`), content, 'utf8')
}

const loaderEntries = works
  .map((work: any) => `  '${work.id}': () => import('./work_chunks/${work.id}'),`)
  .join('\n')
const manifest = `// Generated by scripts/generate_work_chunks.ts\nexport const workImports = {\n${loaderEntries}\n} as const\n`
fs.writeFileSync('src/data/workImportManifest.ts', manifest, 'utf8')
console.log(`Generated ${works.length} independent work modules from ${chapters.length} chapters, ${passages.length} passages and ${sentences.length} sentences, injected with Reading Aids!`)
