import fs from'node:fs';const A=(translation,analysis)=>({translation,analysis}),a={
'mo-zi_ch-13_p-1':A('墨子說：智者必做能使國家百姓治的事、避開使其亂的事。君上施政能取得下情，就能分辨民間善惡、賞善罰暴，國家必治；不得下情，便不能正確賞罰，國家必亂。因此賞罰能否取得下情，不可不察。','本段把尚同的核心重述為信息問題，而非單純服從。「賞不得下之情」脫漏「罰」，依上下文與校本補為「賞罰不得下之情」。'),
'mo-zi_ch-13_p-2':A('要取得下情，只有以尚同一義施政。上古百姓各自為政，一人一義，遂有爭鬥；因此選賢立天子，再置三公、諸侯、卿宰、鄉長家君，並非供其富貴逸樂，而是協助治理刑政與天下人民。','本段從百姓各自為政推導多層官制。原資料「百姓為人」依四庫本等校為「百姓為政」，「助治天助明」校回「助治天民」。'),
'mo-zi_ch-13_p-3':A('如今在上者不能治下，在下者不能事上，是因上下義不同。君上賞某人而百姓毀之，賞不足勸善；君上罰某人而百姓譽之，罰不足止暴。根本原因正是義不同。','獎懲效果取決於共享的正當性判斷；若官民評價相反，權力的賞罰無法形成道德激勵。'),
'mo-zi_ch-13_p-4':A('要統一家義，家君應發布法令：見愛家利家或惡家害家者都須報告；報告愛利者如同共同愛利，不報惡害者等同共同作惡。全家因求賞避罰而報告善惡，家君得以賞善罰暴，家便治理。','此段把尚同落實於家。開頭「賞使家君試用家君」傳本殘缺，孫詒讓收錄「嘗使家人總其身之義」等推校；本文保留底本並在解析說明，不把重構冒充原文。'),
'mo-zi_ch-13_p-5':A('一家治好仍不足，因一國多家，各自以己家為是便會爭亂；所以家君總合家義，上同國君。國君同樣命人報告愛利國與惡賊國者，賞善罰暴，國便治理。','從家到國的升級說明局部共同體仍可能彼此衝突，必須再以更廣的公共利益統合。'),
'mo-zi_ch-13_p-6':A('一國治好仍不足，天下多國各自是己非人，便有戰爭；所以國君把國義上同天子。天子令天下報告愛利天下與惡賊天下者，正確賞罰，天下便治。','國際衝突被解釋為國家私義的擴張；尚同於天子要求把判準提升為「愛利天下」。'),
'mo-zi_ch-13_p-7':A('天下治後，天子還要總合天下之義，上同於天。尚同之道，大用可治天下，中用可治國，小用可治家，大小施行皆不困窮偏邪。','天仍是天子之上的終極標準；家、國、天下的制度同構，也展示墨子認為此道具可伸縮性。'),
'mo-zi_ch-13_p-8':A('治理天下國家應如治理一家，役使天下人民應如使用一人。這不只是墨子之說，先王也以尚同施政。《泰誓》說，見奸邪而知情不報者，罪與奸邪者相等。','本段援引先王之書支持知情報告制度；它強化共同防害，但也顯示尚同高度依賴告發與賞罰。'),
'mo-zi_ch-13_p-9':A('古聖王選良臣為羽翼，使眾人助其視聽，所以謀事、舉事、聲譽都先人一步。一目一耳一手不如雙目雙耳雙手；聖王並非親見千里外，而是藉天下耳目賞遠賢、罰遠暴，使寇亂者無處立足。','所謂聰明如神，實為擴張信息與行動能力。「信身」等詞校說不一，本文保留通行底本，按「擴充一己能力」釋義。'),
'mo-zi_ch-13_p-10':A('墨子說：要使人民尚同，必須急切愛民而任用他們，以誠信維繫，前以富貴引導，後以明罰督率；如此施政，人民想不與上同也辦不到。','本段並列愛、信、賞、罰四項治理手段。首句「愛民不疾」疑有倒誤，校家或讀「必疾」；本文不據推測改動正文。'),
'mo-zi_ch-13_p-11':A('所以墨子說：今日王公士君子若真想行仁義、成為上士，上合聖王之道、下合國家百姓之利，就不可不明察尚同；尚同是施政根本與治國要領。','結語把尚同連回仁義、聖王與百姓利益，要求以是否產生共同公利判斷制度。')};const ids=Object.keys(a),af='src/data/readingAid.ts';let s=fs.readFileSync(af,'utf8');for(const id of ids)if(s.includes(`'${id}': {`))throw Error(id);const marker='\n}\n\nexport function getPassageReadingAid(',ins=Object.entries(a).map(([id,v])=>`  '${id}': ${JSON.stringify(v,null,2).replace(/\n/g,'\n  ')},`).join('\n');fs.writeFileSync(af,s.replace(marker,`\n${ins}\n${marker}`),'utf8');const ef='src/data/editorialReviews.json',e=JSON.parse(fs.readFileSync(ef,'utf8'));e.reviews=e.reviews.filter(r=>!ids.includes(r.passageId));const sources=['https://ctext.org/mozi/identification-with-the-superior-iii/zh','https://ctext.org/mozi-jiangu/shang-tong-xia/zh','https://zh.wikisource.org/zh-hant/%E5%A2%A8%E5%AD%90/%E5%B0%9A%E5%90%8C%E4%B8%8B','https://upload.wikimedia.org/wikipedia/commons/e/ec/SSID-13362508_%E5%A2%A8%E5%AD%90%E6%A0%A1%E6%B3%A8_1.pdf','孫詒讓《墨子閒詁》；吳毓江《墨子校注》'];e.reviews.push(...ids.map(passageId=>({passageId,canonicalText:'verified',translation:'verified',analysis:'verified',sources,reviewedAt:'2026-07-29',notes:passageId==='mo-zi_ch-13_p-4'||passageId==='mo-zi_ch-13_p-10'?'傳本文句殘訛且校說未定，保留通行底本，在解析中列主要推校。':['mo-zi_ch-13_p-1','mo-zi_ch-13_p-2'].includes(passageId)?'依校本修復確證脫誤並重建句子索引。':'依通行本與校注本交叉核對，重寫繁體白話與解析。'})));e.updatedAt='2026-07-29';fs.writeFileSync(ef,`${JSON.stringify(e,null,2)}\n`,'utf8');console.log(`Reviewed ${ids.length} passages in 墨子·尚同下.`)
