// 自動生成之古典音檔中繼資料 (Auto-generated by scripts/generate_audio_files.py)
export interface AudioManifestItem {
  passageId: string
  duration: number
  sizeBytes: number
  voice: string
  rate: string
  url: string
}

export const AUDIO_MANIFEST: Record<string, AudioManifestItem> = {
  "dao-de-jing_ch-1_p-1": {
    "passageId": "dao-de-jing_ch-1_p-1",
    "duration": 13.46,
    "sizeBytes": 134640,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-1_p-1.mp3"
  },
  "dao-de-jing_ch-10_p-1": {
    "passageId": "dao-de-jing_ch-10_p-1",
    "duration": 15.34,
    "sizeBytes": 153360,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-10_p-1.mp3"
  },
  "dao-de-jing_ch-11_p-1": {
    "passageId": "dao-de-jing_ch-11_p-1",
    "duration": 10.43,
    "sizeBytes": 104256,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-11_p-1.mp3"
  },
  "dao-de-jing_ch-12_p-1": {
    "passageId": "dao-de-jing_ch-12_p-1",
    "duration": 8.48,
    "sizeBytes": 84816,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-12_p-1.mp3"
  },
  "dao-de-jing_ch-13_p-1": {
    "passageId": "dao-de-jing_ch-13_p-1",
    "duration": 15.58,
    "sizeBytes": 155808,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-13_p-1.mp3"
  },
  "dao-de-jing_ch-14_p-1": {
    "passageId": "dao-de-jing_ch-14_p-1",
    "duration": 19.28,
    "sizeBytes": 192816,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-14_p-1.mp3"
  },
  "dao-de-jing_ch-15_p-1": {
    "passageId": "dao-de-jing_ch-15_p-1",
    "duration": 17.74,
    "sizeBytes": 177408,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-15_p-1.mp3"
  },
  "dao-de-jing_ch-16_p-1": {
    "passageId": "dao-de-jing_ch-16_p-1",
    "duration": 15.65,
    "sizeBytes": 156528,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-16_p-1.mp3"
  },
  "dao-de-jing_ch-17_p-1": {
    "passageId": "dao-de-jing_ch-17_p-1",
    "duration": 10.64,
    "sizeBytes": 106416,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-17_p-1.mp3"
  },
  "dao-de-jing_ch-18_p-1": {
    "passageId": "dao-de-jing_ch-18_p-1",
    "duration": 5.47,
    "sizeBytes": 54720,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-18_p-1.mp3"
  },
  "dao-de-jing_ch-19_p-1": {
    "passageId": "dao-de-jing_ch-19_p-1",
    "duration": 9.23,
    "sizeBytes": 92304,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-19_p-1.mp3"
  },
  "dao-de-jing_ch-2_p-1": {
    "passageId": "dao-de-jing_ch-2_p-1",
    "duration": 15.8,
    "sizeBytes": 157968,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-2_p-1.mp3"
  },
  "dao-de-jing_ch-20_p-1": {
    "passageId": "dao-de-jing_ch-20_p-1",
    "duration": 28.6,
    "sizeBytes": 285984,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-20_p-1.mp3"
  },
  "dao-de-jing_ch-21_p-1": {
    "passageId": "dao-de-jing_ch-21_p-1",
    "duration": 15.47,
    "sizeBytes": 154656,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-21_p-1.mp3"
  },
  "dao-de-jing_ch-22_p-1": {
    "passageId": "dao-de-jing_ch-22_p-1",
    "duration": 16.6,
    "sizeBytes": 166032,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-22_p-1.mp3"
  },
  "dao-de-jing_ch-23_p-1": {
    "passageId": "dao-de-jing_ch-23_p-1",
    "duration": 18.24,
    "sizeBytes": 182448,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-23_p-1.mp3"
  },
  "dao-de-jing_ch-24_p-1": {
    "passageId": "dao-de-jing_ch-24_p-1",
    "duration": 9.26,
    "sizeBytes": 92592,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-24_p-1.mp3"
  },
  "dao-de-jing_ch-25_p-1": {
    "passageId": "dao-de-jing_ch-25_p-1",
    "duration": 18.0,
    "sizeBytes": 180000,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-25_p-1.mp3"
  },
  "dao-de-jing_ch-26_p-1": {
    "passageId": "dao-de-jing_ch-26_p-1",
    "duration": 10.05,
    "sizeBytes": 100512,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-26_p-1.mp3"
  },
  "dao-de-jing_ch-27_p-1": {
    "passageId": "dao-de-jing_ch-27_p-1",
    "duration": 16.59,
    "sizeBytes": 165888,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-27_p-1.mp3"
  },
  "dao-de-jing_ch-28_p-1": {
    "passageId": "dao-de-jing_ch-28_p-1",
    "duration": 18.62,
    "sizeBytes": 186192,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-28_p-1.mp3"
  },
  "dao-de-jing_ch-29_p-1": {
    "passageId": "dao-de-jing_ch-29_p-1",
    "duration": 11.46,
    "sizeBytes": 114624,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-29_p-1.mp3"
  },
  "dao-de-jing_ch-3_p-1": {
    "passageId": "dao-de-jing_ch-3_p-1",
    "duration": 13.58,
    "sizeBytes": 135792,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-3_p-1.mp3"
  },
  "dao-de-jing_ch-30_p-1": {
    "passageId": "dao-de-jing_ch-30_p-1",
    "duration": 16.53,
    "sizeBytes": 165312,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-30_p-1.mp3"
  },
  "dao-de-jing_ch-31_p-1": {
    "passageId": "dao-de-jing_ch-31_p-1",
    "duration": 22.25,
    "sizeBytes": 222480,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-31_p-1.mp3"
  },
  "dao-de-jing_ch-32_p-1": {
    "passageId": "dao-de-jing_ch-32_p-1",
    "duration": 13.71,
    "sizeBytes": 137088,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-32_p-1.mp3"
  },
  "dao-de-jing_ch-33_p-1": {
    "passageId": "dao-de-jing_ch-33_p-1",
    "duration": 9.76,
    "sizeBytes": 97632,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-33_p-1.mp3"
  },
  "dao-de-jing_ch-34_p-1": {
    "passageId": "dao-de-jing_ch-34_p-1",
    "duration": 11.36,
    "sizeBytes": 113616,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-34_p-1.mp3"
  },
  "dao-de-jing_ch-35_p-1": {
    "passageId": "dao-de-jing_ch-35_p-1",
    "duration": 9.42,
    "sizeBytes": 94176,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-35_p-1.mp3"
  },
  "dao-de-jing_ch-36_p-1": {
    "passageId": "dao-de-jing_ch-36_p-1",
    "duration": 10.77,
    "sizeBytes": 107712,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-36_p-1.mp3"
  },
  "dao-de-jing_ch-37_p-1": {
    "passageId": "dao-de-jing_ch-37_p-1",
    "duration": 10.47,
    "sizeBytes": 104688,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-37_p-1.mp3"
  },
  "dao-de-jing_ch-38_p-1": {
    "passageId": "dao-de-jing_ch-38_p-1",
    "duration": 24.7,
    "sizeBytes": 246960,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-38_p-1.mp3"
  },
  "dao-de-jing_ch-39_p-1": {
    "passageId": "dao-de-jing_ch-39_p-1",
    "duration": 25.14,
    "sizeBytes": 251424,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-39_p-1.mp3"
  },
  "dao-de-jing_ch-4_p-1": {
    "passageId": "dao-de-jing_ch-4_p-1",
    "duration": 9.92,
    "sizeBytes": 99216,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-4_p-1.mp3"
  },
  "dao-de-jing_ch-40_p-1": {
    "passageId": "dao-de-jing_ch-40_p-1",
    "duration": 4.36,
    "sizeBytes": 43632,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-40_p-1.mp3"
  },
  "dao-de-jing_ch-41_p-1": {
    "passageId": "dao-de-jing_ch-41_p-1",
    "duration": 17.9,
    "sizeBytes": 178992,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-41_p-1.mp3"
  },
  "dao-de-jing_ch-42_p-1": {
    "passageId": "dao-de-jing_ch-42_p-1",
    "duration": 15.13,
    "sizeBytes": 151344,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-42_p-1.mp3"
  },
  "dao-de-jing_ch-43_p-1": {
    "passageId": "dao-de-jing_ch-43_p-1",
    "duration": 7.27,
    "sizeBytes": 72720,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-43_p-1.mp3"
  },
  "dao-de-jing_ch-44_p-1": {
    "passageId": "dao-de-jing_ch-44_p-1",
    "duration": 8.88,
    "sizeBytes": 88848,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-44_p-1.mp3"
  },
  "dao-de-jing_ch-45_p-1": {
    "passageId": "dao-de-jing_ch-45_p-1",
    "duration": 9.68,
    "sizeBytes": 96768,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-45_p-1.mp3"
  },
  "dao-de-jing_ch-46_p-1": {
    "passageId": "dao-de-jing_ch-46_p-1",
    "duration": 8.4,
    "sizeBytes": 83952,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-46_p-1.mp3"
  },
  "dao-de-jing_ch-47_p-1": {
    "passageId": "dao-de-jing_ch-47_p-1",
    "duration": 7.8,
    "sizeBytes": 78048,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-47_p-1.mp3"
  },
  "dao-de-jing_ch-48_p-1": {
    "passageId": "dao-de-jing_ch-48_p-1",
    "duration": 8.61,
    "sizeBytes": 86112,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-48_p-1.mp3"
  },
  "dao-de-jing_ch-49_p-1": {
    "passageId": "dao-de-jing_ch-49_p-1",
    "duration": 13.09,
    "sizeBytes": 130896,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-49_p-1.mp3"
  },
  "dao-de-jing_ch-5_p-1": {
    "passageId": "dao-de-jing_ch-5_p-1",
    "duration": 9.12,
    "sizeBytes": 91152,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-5_p-1.mp3"
  },
  "dao-de-jing_ch-50_p-1": {
    "passageId": "dao-de-jing_ch-50_p-1",
    "duration": 16.85,
    "sizeBytes": 168480,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-50_p-1.mp3"
  },
  "dao-de-jing_ch-51_p-1": {
    "passageId": "dao-de-jing_ch-51_p-1",
    "duration": 14.36,
    "sizeBytes": 143568,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-51_p-1.mp3"
  },
  "dao-de-jing_ch-52_p-1": {
    "passageId": "dao-de-jing_ch-52_p-1",
    "duration": 16.07,
    "sizeBytes": 160704,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-52_p-1.mp3"
  },
  "dao-de-jing_ch-53_p-1": {
    "passageId": "dao-de-jing_ch-53_p-1",
    "duration": 11.15,
    "sizeBytes": 111456,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-53_p-1.mp3"
  },
  "dao-de-jing_ch-54_p-1": {
    "passageId": "dao-de-jing_ch-54_p-1",
    "duration": 16.89,
    "sizeBytes": 168912,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-54_p-1.mp3"
  },
  "dao-de-jing_ch-55_p-1": {
    "passageId": "dao-de-jing_ch-55_p-1",
    "duration": 17.44,
    "sizeBytes": 174384,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-55_p-1.mp3"
  },
  "dao-de-jing_ch-56_p-1": {
    "passageId": "dao-de-jing_ch-56_p-1",
    "duration": 12.93,
    "sizeBytes": 129312,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-56_p-1.mp3"
  },
  "dao-de-jing_ch-57_p-1": {
    "passageId": "dao-de-jing_ch-57_p-1",
    "duration": 16.68,
    "sizeBytes": 166752,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-57_p-1.mp3"
  },
  "dao-de-jing_ch-58_p-1": {
    "passageId": "dao-de-jing_ch-58_p-1",
    "duration": 15.45,
    "sizeBytes": 154512,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-58_p-1.mp3"
  },
  "dao-de-jing_ch-59_p-1": {
    "passageId": "dao-de-jing_ch-59_p-1",
    "duration": 10.73,
    "sizeBytes": 107280,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-59_p-1.mp3"
  },
  "dao-de-jing_ch-6_p-1": {
    "passageId": "dao-de-jing_ch-6_p-1",
    "duration": 5.99,
    "sizeBytes": 59904,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-6_p-1.mp3"
  },
  "dao-de-jing_ch-60_p-1": {
    "passageId": "dao-de-jing_ch-60_p-1",
    "duration": 8.99,
    "sizeBytes": 89856,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-60_p-1.mp3"
  },
  "dao-de-jing_ch-61_p-1": {
    "passageId": "dao-de-jing_ch-61_p-1",
    "duration": 15.81,
    "sizeBytes": 158112,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-61_p-1.mp3"
  },
  "dao-de-jing_ch-62_p-1": {
    "passageId": "dao-de-jing_ch-62_p-1",
    "duration": 16.56,
    "sizeBytes": 165600,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-62_p-1.mp3"
  },
  "dao-de-jing_ch-63_p-1": {
    "passageId": "dao-de-jing_ch-63_p-1",
    "duration": 15.83,
    "sizeBytes": 158256,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-63_p-1.mp3"
  },
  "dao-de-jing_ch-64_p-1": {
    "passageId": "dao-de-jing_ch-64_p-1",
    "duration": 24.21,
    "sizeBytes": 242064,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-64_p-1.mp3"
  },
  "dao-de-jing_ch-65_p-1": {
    "passageId": "dao-de-jing_ch-65_p-1",
    "duration": 14.7,
    "sizeBytes": 147024,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-65_p-1.mp3"
  },
  "dao-de-jing_ch-66_p-1": {
    "passageId": "dao-de-jing_ch-66_p-1",
    "duration": 13.51,
    "sizeBytes": 135072,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-66_p-1.mp3"
  },
  "dao-de-jing_ch-67_p-1": {
    "passageId": "dao-de-jing_ch-67_p-1",
    "duration": 21.0,
    "sizeBytes": 209952,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-67_p-1.mp3"
  },
  "dao-de-jing_ch-68_p-1": {
    "passageId": "dao-de-jing_ch-68_p-1",
    "duration": 8.38,
    "sizeBytes": 83808,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-68_p-1.mp3"
  },
  "dao-de-jing_ch-69_p-1": {
    "passageId": "dao-de-jing_ch-69_p-1",
    "duration": 11.32,
    "sizeBytes": 113184,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-69_p-1.mp3"
  },
  "dao-de-jing_ch-7_p-1": {
    "passageId": "dao-de-jing_ch-7_p-1",
    "duration": 9.85,
    "sizeBytes": 98496,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-7_p-1.mp3"
  },
  "dao-de-jing_ch-70_p-1": {
    "passageId": "dao-de-jing_ch-70_p-1",
    "duration": 11.09,
    "sizeBytes": 110880,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-70_p-1.mp3"
  },
  "dao-de-jing_ch-71_p-1": {
    "passageId": "dao-de-jing_ch-71_p-1",
    "duration": 7.01,
    "sizeBytes": 70128,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-71_p-1.mp3"
  },
  "dao-de-jing_ch-72_p-1": {
    "passageId": "dao-de-jing_ch-72_p-1",
    "duration": 9.75,
    "sizeBytes": 97488,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-72_p-1.mp3"
  },
  "dao-de-jing_ch-73_p-1": {
    "passageId": "dao-de-jing_ch-73_p-1",
    "duration": 13.33,
    "sizeBytes": 133344,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-73_p-1.mp3"
  },
  "dao-de-jing_ch-74_p-1": {
    "passageId": "dao-de-jing_ch-74_p-1",
    "duration": 10.61,
    "sizeBytes": 106128,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-74_p-1.mp3"
  },
  "dao-de-jing_ch-75_p-1": {
    "passageId": "dao-de-jing_ch-75_p-1",
    "duration": 10.47,
    "sizeBytes": 104688,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-75_p-1.mp3"
  },
  "dao-de-jing_ch-76_p-1": {
    "passageId": "dao-de-jing_ch-76_p-1",
    "duration": 11.88,
    "sizeBytes": 118800,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-76_p-1.mp3"
  },
  "dao-de-jing_ch-77_p-1": {
    "passageId": "dao-de-jing_ch-77_p-1",
    "duration": 15.39,
    "sizeBytes": 153936,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-77_p-1.mp3"
  },
  "dao-de-jing_ch-78_p-1": {
    "passageId": "dao-de-jing_ch-78_p-1",
    "duration": 12.08,
    "sizeBytes": 120816,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-78_p-1.mp3"
  },
  "dao-de-jing_ch-79_p-1": {
    "passageId": "dao-de-jing_ch-79_p-1",
    "duration": 8.76,
    "sizeBytes": 87552,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-79_p-1.mp3"
  },
  "dao-de-jing_ch-8_p-1": {
    "passageId": "dao-de-jing_ch-8_p-1",
    "duration": 11.07,
    "sizeBytes": 110736,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-8_p-1.mp3"
  },
  "dao-de-jing_ch-80_p-1": {
    "passageId": "dao-de-jing_ch-80_p-1",
    "duration": 14.82,
    "sizeBytes": 148176,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-80_p-1.mp3"
  },
  "dao-de-jing_ch-81_p-1": {
    "passageId": "dao-de-jing_ch-81_p-1",
    "duration": 11.52,
    "sizeBytes": 115200,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-81_p-1.mp3"
  },
  "dao-de-jing_ch-9_p-1": {
    "passageId": "dao-de-jing_ch-9_p-1",
    "duration": 8.21,
    "sizeBytes": 82080,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/dao-de-jing/dao-de-jing_ch-9_p-1.mp3"
  },
  "da-xue_ch-1_p-1": {
    "passageId": "da-xue_ch-1_p-1",
    "duration": 9.07,
    "sizeBytes": 90720,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/da-xue/da-xue_ch-1_p-1.mp3"
  },
  "da-xue_ch-1_p-2": {
    "passageId": "da-xue_ch-1_p-2",
    "duration": 34.5,
    "sizeBytes": 345024,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/da-xue/da-xue_ch-1_p-2.mp3"
  },
  "da-xue_ch-10_p-11": {
    "passageId": "da-xue_ch-10_p-11",
    "duration": 48.82,
    "sizeBytes": 488160,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/da-xue/da-xue_ch-10_p-11.mp3"
  },
  "da-xue_ch-11_p-12": {
    "passageId": "da-xue_ch-11_p-12",
    "duration": 117.42,
    "sizeBytes": 1174176,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/da-xue/da-xue_ch-11_p-12.mp3"
  },
  "da-xue_ch-2_p-3": {
    "passageId": "da-xue_ch-2_p-3",
    "duration": 4.59,
    "sizeBytes": 45936,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/da-xue/da-xue_ch-2_p-3.mp3"
  },
  "da-xue_ch-3_p-4": {
    "passageId": "da-xue_ch-3_p-4",
    "duration": 7.04,
    "sizeBytes": 70416,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/da-xue/da-xue_ch-3_p-4.mp3"
  },
  "da-xue_ch-4_p-5": {
    "passageId": "da-xue_ch-4_p-5",
    "duration": 38.48,
    "sizeBytes": 384768,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/da-xue/da-xue_ch-4_p-5.mp3"
  },
  "da-xue_ch-5_p-6": {
    "passageId": "da-xue_ch-5_p-6",
    "duration": 6.28,
    "sizeBytes": 62784,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/da-xue/da-xue_ch-5_p-6.mp3"
  },
  "da-xue_ch-6_p-7": {
    "passageId": "da-xue_ch-6_p-7",
    "duration": 2.12,
    "sizeBytes": 21168,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/da-xue/da-xue_ch-6_p-7.mp3"
  },
  "da-xue_ch-7_p-8": {
    "passageId": "da-xue_ch-7_p-8",
    "duration": 21.56,
    "sizeBytes": 215568,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/da-xue/da-xue_ch-7_p-8.mp3"
  },
  "da-xue_ch-8_p-9": {
    "passageId": "da-xue_ch-8_p-9",
    "duration": 13.02,
    "sizeBytes": 130176,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/da-xue/da-xue_ch-8_p-9.mp3"
  },
  "da-xue_ch-9_p-10": {
    "passageId": "da-xue_ch-9_p-10",
    "duration": 14.11,
    "sizeBytes": 141120,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/da-xue/da-xue_ch-9_p-10.mp3"
  },
  "lun-yu_ch-1_p-1": {
    "passageId": "lun-yu_ch-1_p-1",
    "duration": 6.67,
    "sizeBytes": 66672,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/lun-yu/lun-yu_ch-1_p-1.mp3"
  },
  "lun-yu_ch-1_p-2": {
    "passageId": "lun-yu_ch-1_p-2",
    "duration": 9.52,
    "sizeBytes": 95184,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/lun-yu/lun-yu_ch-1_p-2.mp3"
  },
  "lun-yu_ch-1_p-3": {
    "passageId": "lun-yu_ch-1_p-3",
    "duration": 2.64,
    "sizeBytes": 26352,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/lun-yu/lun-yu_ch-1_p-3.mp3"
  },
  "lun-yu_ch-1_p-4": {
    "passageId": "lun-yu_ch-1_p-4",
    "duration": 5.89,
    "sizeBytes": 58896,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/lun-yu/lun-yu_ch-1_p-4.mp3"
  },
  "lun-yu_ch-1_p-5": {
    "passageId": "lun-yu_ch-1_p-5",
    "duration": 4.18,
    "sizeBytes": 41760,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/lun-yu/lun-yu_ch-1_p-5.mp3"
  },
  "lun-yu_ch-1_p-6": {
    "passageId": "lun-yu_ch-1_p-6",
    "duration": 6.36,
    "sizeBytes": 63648,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/lun-yu/lun-yu_ch-1_p-6.mp3"
  },
  "lun-yu_ch-1_p-7": {
    "passageId": "lun-yu_ch-1_p-7",
    "duration": 7.16,
    "sizeBytes": 71568,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/lun-yu/lun-yu_ch-1_p-7.mp3"
  },
  "lun-yu_ch-1_p-8": {
    "passageId": "lun-yu_ch-1_p-8",
    "duration": 6.71,
    "sizeBytes": 67104,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/lun-yu/lun-yu_ch-1_p-8.mp3"
  },
  "lun-yu_ch-1_p-9": {
    "passageId": "lun-yu_ch-1_p-9",
    "duration": 2.85,
    "sizeBytes": 28512,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/lun-yu/lun-yu_ch-1_p-9.mp3"
  },
  "lun-yu_ch-1_p-10": {
    "passageId": "lun-yu_ch-1_p-10",
    "duration": 10.84,
    "sizeBytes": 108432,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/lun-yu/lun-yu_ch-1_p-10.mp3"
  },
  "lun-yu_ch-1_p-11": {
    "passageId": "lun-yu_ch-1_p-11",
    "duration": 5.11,
    "sizeBytes": 51120,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/lun-yu/lun-yu_ch-1_p-11.mp3"
  },
  "lun-yu_ch-1_p-12": {
    "passageId": "lun-yu_ch-1_p-12",
    "duration": 8.06,
    "sizeBytes": 80640,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/lun-yu/lun-yu_ch-1_p-12.mp3"
  },
  "lun-yu_ch-1_p-13": {
    "passageId": "lun-yu_ch-1_p-13",
    "duration": 5.31,
    "sizeBytes": 53136,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/lun-yu/lun-yu_ch-1_p-13.mp3"
  },
  "lun-yu_ch-1_p-14": {
    "passageId": "lun-yu_ch-1_p-14",
    "duration": 5.37,
    "sizeBytes": 53712,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/lun-yu/lun-yu_ch-1_p-14.mp3"
  },
  "lun-yu_ch-1_p-15": {
    "passageId": "lun-yu_ch-1_p-15",
    "duration": 14.27,
    "sizeBytes": 142704,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/lun-yu/lun-yu_ch-1_p-15.mp3"
  },
  "lun-yu_ch-1_p-16": {
    "passageId": "lun-yu_ch-1_p-16",
    "duration": 2.91,
    "sizeBytes": 29088,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/lun-yu/lun-yu_ch-1_p-16.mp3"
  },
  "art-of-war_ch-1_p-1": {
    "passageId": "art-of-war_ch-1_p-1",
    "duration": 4.32,
    "sizeBytes": 43200,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/art-of-war/art-of-war_ch-1_p-1.mp3"
  },
  "art-of-war_ch-1_p-2": {
    "passageId": "art-of-war_ch-1_p-2",
    "duration": 5.56,
    "sizeBytes": 55584,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/art-of-war/art-of-war_ch-1_p-2.mp3"
  },
  "art-of-war_ch-1_p-3": {
    "passageId": "art-of-war_ch-1_p-3",
    "duration": 19.09,
    "sizeBytes": 190944,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/art-of-war/art-of-war_ch-1_p-3.mp3"
  },
  "art-of-war_ch-1_p-4": {
    "passageId": "art-of-war_ch-1_p-4",
    "duration": 12.93,
    "sizeBytes": 129312,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/art-of-war/art-of-war_ch-1_p-4.mp3"
  },
  "art-of-war_ch-1_p-5": {
    "passageId": "art-of-war_ch-1_p-5",
    "duration": 3.89,
    "sizeBytes": 38880,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/art-of-war/art-of-war_ch-1_p-5.mp3"
  },
  "art-of-war_ch-1_p-6": {
    "passageId": "art-of-war_ch-1_p-6",
    "duration": 14.26,
    "sizeBytes": 142560,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/art-of-war/art-of-war_ch-1_p-6.mp3"
  },
  "art-of-war_ch-1_p-7": {
    "passageId": "art-of-war_ch-1_p-7",
    "duration": 7.95,
    "sizeBytes": 79488,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/art-of-war/art-of-war_ch-1_p-7.mp3"
  },
  "gu-wen-guan-zhi_ch-1_p-1": {
    "passageId": "gu-wen-guan-zhi_ch-1_p-1",
    "duration": 10.14,
    "sizeBytes": 101376,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/gu-wen-guan-zhi/gu-wen-guan-zhi_ch-1_p-1.mp3"
  },
  "gu-wen-guan-zhi_ch-1_p-2": {
    "passageId": "gu-wen-guan-zhi_ch-1_p-2",
    "duration": 7.63,
    "sizeBytes": 76320,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/gu-wen-guan-zhi/gu-wen-guan-zhi_ch-1_p-2.mp3"
  },
  "gu-wen-guan-zhi_ch-1_p-3": {
    "passageId": "gu-wen-guan-zhi_ch-1_p-3",
    "duration": 20.25,
    "sizeBytes": 202464,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/gu-wen-guan-zhi/gu-wen-guan-zhi_ch-1_p-3.mp3"
  },
  "gu-wen-guan-zhi_ch-1_p-4": {
    "passageId": "gu-wen-guan-zhi_ch-1_p-4",
    "duration": 11.3,
    "sizeBytes": 113040,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/gu-wen-guan-zhi/gu-wen-guan-zhi_ch-1_p-4.mp3"
  },
  "gu-wen-guan-zhi_ch-1_p-5": {
    "passageId": "gu-wen-guan-zhi_ch-1_p-5",
    "duration": 7.16,
    "sizeBytes": 71568,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/gu-wen-guan-zhi/gu-wen-guan-zhi_ch-1_p-5.mp3"
  },
  "gu-wen-guan-zhi_ch-1_p-6": {
    "passageId": "gu-wen-guan-zhi_ch-1_p-6",
    "duration": 12.34,
    "sizeBytes": 123408,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/gu-wen-guan-zhi/gu-wen-guan-zhi_ch-1_p-6.mp3"
  },
  "gu-wen-guan-zhi_ch-1_p-7": {
    "passageId": "gu-wen-guan-zhi_ch-1_p-7",
    "duration": 9.49,
    "sizeBytes": 94896,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/gu-wen-guan-zhi/gu-wen-guan-zhi_ch-1_p-7.mp3"
  },
  "gu-wen-guan-zhi_ch-1_p-8": {
    "passageId": "gu-wen-guan-zhi_ch-1_p-8",
    "duration": 4.19,
    "sizeBytes": 41904,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/gu-wen-guan-zhi/gu-wen-guan-zhi_ch-1_p-8.mp3"
  },
  "gu-wen-guan-zhi_ch-1_p-9": {
    "passageId": "gu-wen-guan-zhi_ch-1_p-9",
    "duration": 18.72,
    "sizeBytes": 187200,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/gu-wen-guan-zhi/gu-wen-guan-zhi_ch-1_p-9.mp3"
  },
  "gu-wen-guan-zhi_ch-1_p-10": {
    "passageId": "gu-wen-guan-zhi_ch-1_p-10",
    "duration": 5.5,
    "sizeBytes": 55008,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/gu-wen-guan-zhi/gu-wen-guan-zhi_ch-1_p-10.mp3"
  },
  "gu-wen-guan-zhi_ch-1_p-11": {
    "passageId": "gu-wen-guan-zhi_ch-1_p-11",
    "duration": 6.83,
    "sizeBytes": 68256,
    "voice": "zh-TW-YunJheNeural",
    "rate": "-8%",
    "url": "audio/gu-wen-guan-zhi/gu-wen-guan-zhi_ch-1_p-11.mp3"
  }
}

/**
 * 檢查特定段落是否存在高品質實體語音檔
 */
export function getAudioFileMeta(passageId: string): AudioManifestItem | undefined {
  return AUDIO_MANIFEST[passageId]
}

/**
 * 取得特定段落的音檔完整 URL（自適應 Vite BASE_URL）
 */
export function getAudioFileUrl(passageId: string): string | undefined {
  const meta = AUDIO_MANIFEST[passageId]
  if (!meta) return undefined
  const base = import.meta.env.BASE_URL || '/'
  const cleanBase = base.endsWith('/') ? base : base + '/'
  return `${cleanBase}${meta.url}`
}
